sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "stable"
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run coveralls
branches:
  only:
    - master
